### ISSUE TITLE
Sensors not working?

### ISSUE THREAD

**Issue by messenger2011** [willza3/macOS-strix-B450i#1]
Hi there,

Thank you for your works. I'm trying to monitor temp using HWMonitor but nothing show up (CPU Temp, GPU Temp, Fan Speed...). Any guide or update to fix this issue, please?

Thank you.

**Comment by messenger2011** [comment]
Fixed by https://github.com/trulyspinach/SMCAMDProcessor

**Comment by willza3** [comment]
Thanks for making me aware of this! I'll test it out today and add it to the next release 👍
