### ISSUE TITLE
Some issues Boot and Keyboard, mouse...

### ISSUE THREAD

**Issue by conchodaus** [willza3/macOS-strix-B450i#11]
Hi willza3,

I would like to thank you for your efi. I have the same hardware as you. Working great. But I have 3 issues:
1.When starting Boot, the bar under the apple runs very slowly. it takes 2-3 minutes to boot up the macos screen and then it will lose the keyboard (this action only occasionally happens)
I see "00: 000 00: 000 OCB: Failed to match a default boot option" in efi log.
And I got a new blinking flashed into the boot screen MACOS (at 0:17 video below)
See video: https://www.dropbox.com/s/cwgcblxf89q6dwc/Video%205-20-20%2C%2017%2046%2044.mov?dl=0

2. And sometimes the computer mouse is disconnected or Stuck at the sreen.(at 0:07s in the video below)

https://www.dropbox.com/s/l2jpxvy9cduu6ov/Video%205-21-20%2C%2006%2029%2031.mov?dl=0

Are u having troubles like me?

Ryzen R5 3600 
B450-I Gaming Rog Strix – updated lastest verion bios.
AMD RX 580 nitro+ 8gb

**Comment by willza3** [comment]
Still having these issues? Make sure you running the latest EFI files and let me know. I haven't had a slow boot on macOS however sometimes my mouse will disconnect and I'll have to physically reconnect it...

Sorry for the late response! I'll keep this issue open for now...

**Comment by conchodaus** [comment]
I have 4 issues.
1. Slow booting: i plug my keyboard usb to hub 3.0. It solved.
2. Mouse lagging: Disable kext nvmefix, AMDCPU, AMDSMC...it solves
3. My mouse will disconnect and I'll have to physically reconnect it...(like you). 
4. Sleep not working... can't wake after sleep.

I patched full dsdt, remapping usb port but (3), (4), not solve...
i running your efi and patch dsdt.

**Comment by willza3** [comment]
#3 shouldn't be a permanent disconnect now just a few seconds with OpenCore 0.5.9 (at least for me)

Closing issue as other issues are now resolved 👍
