### ISSUE TITLE
CSM Problem

### ISSUE THREAD

**Issue by notOops** [willza3/macOS-strix-B450i#12]
I have 2 m2 nvme ssd. I want to install on the second one. But when set csm to disable, the second m2 become the external storage. So, not work. When I enable it, the new version couldn't work(even can't reinstall).Is there any solution?

**Comment by willza3** [comment]
Try [adding this SSDT](https://www.dropbox.com/s/uqhnol80uu6o6t2/SSDT-NVME.aml.zip?dl=0) to your EFI folder. (Add to your ACPI folder and update config.plist)

**Comment by notOops** [comment]
Sorry it seems not to be the csm caused. I recorded and see that "setting nvram ... rtc-balcklist not found", what‘s the problem? I am also the b450i 2600x, only the gpu 5700xt(it is no driver required)

**Comment by willza3** [comment]
Does the issue still happen with OpenCore 0.5.9?
