### ISSUE TITLE
OC0.5.9 is outed,can  update to the  New Edition？

### ISSUE THREAD

**Issue by 158212892** [willza3/macOS-strix-B450i#14]

**Comment by scottdrmyers** [comment]
It will be updated, but it's also very easy for you to update it yourself by copying data out of the config file and simply replacing the files in 0.5.9 or any newer version going forward.

The documentation is located here: https://github.com/dortania

**Comment by willza3** [comment]
Yeah, I'll be updating the configuration to 0.5.9 at some point today or tomorrow (depending when I have free time) I'll close this issue when I've done it.

**Comment by timocapa** [comment]
happy pride month

**Comment by 158212892** [comment]
OK，I'll wait😂😂
