### ISSUE TITLE
Display lagging

### ISSUE THREAD

**Issue by EfraimLA** [willza3/macOS-strix-B450i#15]
When i see movies or videos of high consume resources (HDR or 4k) display goes lagging, and interacting with machine is not just smooth... Could be a problem with GPU? I've a ASRock RX580 8GB OC

This doesn't happen with windows nor Linux, could give some support please?

**Comment by willza3** [comment]
I'm not sure what would be causing this as the RX580 is natively supported on macOS. Does the issue still persist on OpenCore 0.5.9?

**Comment by EfraimLA** [comment]
Yes, it's not much but compared with a MBP there's difference, btw i've a ryzen 7 2700X

**Comment by tranhoanvo** [comment]
I'm not sure if it's count on 1080p display but I'm using ryzen 3500 w/ RX580 8G Gaming X, HDR and 4K on my 1080p display are smooth, no problems.

**Comment by willza3** [comment]
Does this happen when you use the `iMacPro1,1` SMBIOS?

From my personal testing, `iMacPro1,1` actually had the best Geekbench scores compared to other SMBIOS (including `MacPro7,1`) but YMMV.

**Comment by EfraimLA** [comment]
It's the same I also did benchmark with iMacPro1,1 y MacPro7,1 but got better score with 7,1 so I used it but I'm thinking switch to iMacPro1,1 due memory RAM error notification

EDIT: if I want to change smbios must i reinstall macOS?

**Comment by willza3** [comment]
> EDIT: if I want to change smbios must i reinstall macOS?

No, you can switch it on the fly, but I would sign out of iCloud first!
