### ISSUE TITLE
Audio devices not working

### ISSUE THREAD

**Issue by EfraimLA** [willza3/macOS-strix-B450i#16]
After updating to 0.5.9 audio isn't working, also im using Mac7,1 as SMBIOS

![20200603_150715](https://user-images.githubusercontent.com/46459026/83684783-3b3cff80-a5ad-11ea-92f0-2dbec8d24e5a.jpg)

**Comment by willza3** [comment]
Thanks for letting me know 😅  Latest commit should fix this now, is it working on your end?
