### ISSUE TITLE
no internet after sleep wake

### ISSUE THREAD

**Issue by blacksea1206** [willza3/macOS-strix-B450i#17]
I had no issue before the 10.15.5 and 0.5.9, 
but I can't get any internet connection after the sleep-wake.
I'm using the same motherboard b450-i Strix and the onboard LAN.
Does anybody have any info on this issue?

**Comment by willza3** [comment]
Just out of interest, what CPU are you using? Sleep doesn't work for me at all so not sure I can really help with fixing this 😓

**Comment by blacksea1206** [comment]
https://wccftech.com/fix-internet-not-working-after-waking-mac/

Hi guys,
For me the link above solved the problem. Now it works great :)

I was using 3600X, and was working great.
And working great as well now :)
