### ISSUE TITLE
Audio not working

### ISSUE THREAD

**Issue by Qerope** [willza3/macOS-strix-B450i#18]
This new version has some problem with Audio, B450-f no audio input or output. BTW thank you so much for this build

**Comment by willza3** [comment]
Do you have the latest patch to the config plist, I messed up audio with the 0.5.9 update.
I don't have a B450-F unfortunately so can't test anything on my end 😶

[Link](https://github.com/willza3/macOS-strix-B450i/commit/e721a9f6af86bdd64d303e6ed1502808ba79ee95)

**Comment by conchodaus** [comment]
> This new version has some problem with Audio, B450-f no audio input or output. BTW thank you so much for this build

Case1:You must find true pciroot for audio then edit DevicePropertise in config.plist.( open in hackintool and tap to tab pcie. Find pci)
Case 2: add alcid=7 to boot arg

**Comment by Qerope** [comment]
> Do you have the latest patch to the config plist, I messed up audio with the 0.5.9 update.
> I don't have a B450-F unfortunately so can't test anything on my end 😶
> 
> [Link](https://github.com/willza3/macOS-strix-B450i/commit/e721a9f6af86bdd64d303e6ed1502808ba79ee95)

Yes, I’m using the latest update and checked if audio patch is applied correctly. I’ve been using an older version with OC 0.5.8 and audio was nice.
I’m using 3600x.

**Comment by Qerope** [comment]
> > This new version has some problem with Audio, B450-f no audio input or output. BTW thank you so much for this build
> 
> Case1:You must find true pciroot for audio then edit DevicePropertise in config.plist.( open in hackintool and tap to tab pcie. Find pci)
> Case 2: add alcid=7 to boot arg

It's working now! Used hackintool and changed PciRoot(0x0)/Pci(0x8,0x1)/Pci(0x0,0x3) to PciRoot(0x0)/Pci(0x8,0x1)/Pci(0x0,0x4). Thanks for help
