### ISSUE TITLE
Success not an issue: Share my hardware

### ISSUE THREAD

**Issue by Gizmo648** [willza3/macOS-strix-B450i#2]
I hope this is useful. Thanks:  https://github.com/willza3/macOS-strix-B450i

Running Catalina 10.15.3
MB : Asus ROG Strix B450-F
CPU: Ryzen 7 2700x
Ram : Corsair Vengance 8GBx4=32GB
HD : Seagate Barracuda 2TB (Data)
SSD : PNY 120 GB (MacOS)
Power Supply : Corsair CX750 M
Graph Card : Sapphire RX 570 8GB
WIFi: USB Adapter TL-WN823N
Case: Corsair Carbide Spec 06

**Comment by Gizmo648** [comment]
Ryzentosh works wonderfully I don't have a camera or microphone.
Running adobe photoshop, Affinity Photo, Davinci Resolve,
elmedia player, clean my mac, etc.
I have not tried ethernet or facetime because I either have a camera or video.
Everything else works perfect
Thanks a lot man..

**Comment by Gizmo648** [comment]
<img width="585" alt="Screen Shot 2020-03-12 at 8 45 34" src="https://user-images.githubusercontent.com/25337476/76533696-1158be80-643e-11ea-9859-d29e84ee7fe4.png">

**Comment by willza3** [comment]
Thanks for letting me know it works on the B450-F! 🥰
