### ISSUE TITLE
Audio issue on similar motherboard

### ISSUE THREAD

**Issue by gungun974** [willza3/macOS-strix-B450i#20]
Hello.
I bought a ROG Strix X570-E Gaming and I managed to install MacOS.
However, only my sound card does not work and I don't know how i can make it work.
I already read the opencore guide but I don't understand what i should do.
But I saw your Asus Strix B450-i has the same sound card (SupremeFX S1220A) than me but also that you had managed to make it work.
So my question is how you got this and can you explained to me ?

**Comment by willza3** [comment]
Try using a different codec, S1220A supports 1, 2, 3, 5, 7, 11, 20 and 21. You might need to delete the audio PciRoot in Device Properties ➡️ Add and use AppleALC bootarg instead. 

I can't help you otherwise because I don't own that motherboard.

**Comment by conchodaus** [comment]
> Hello.
> I bought a ROG Strix X570-E Gaming and I managed to install MacOS.
> However, only my sound card does not work and I don't know how i can make it work.
> I already read the opencore guide but I don't understand what i should do.
> But I saw your Asus Strix B450-i has the same sound card (SupremeFX S1220A) than me but also that you had managed to make it work.
> So my question is how you got this and can you explained to me ?

Every Mainboard Audio PCIroot is different. You must find true PCIroot and edit theme in "Device Propertise" in config.plist (Use apps "Hackintool" to find this at tab "PCIE") Or add bootflag: alcid=x   (x can be 1.2.3.5.7.11.20.21). test every number.

**Comment by carlosxfigueroa** [comment]
you can use this to find your pcie audio device also https://github.com/acidanthera/gfxutil/releases
and follow this guide https://dortania.github.io/OpenCore-Desktop-Guide/post-install/audio.html

**Comment by gungun974** [comment]
Okay i found something.
When i create my Opencore config, i had need to disable one of my graphics card (NVIDIA) with this guide
https://dortania.github.io/OpenCore-Desktop-Guide/extras/spoof.html
But when i execute what willza3 say to me. I delete unintentionally my patch for graphics card. And something verry strange, my Audio card works, I don't know why disable a graphiics card break AppleALC bootarg.
Do you have an idea of why ?

**Comment by gungun974** [comment]
I never resolve this problem but I have change my sound configuration so this problem is not related to me anymore.
