### ISSUE TITLE
Green screen

### ISSUE THREAD

**Issue by Gizmo648** [willza3/macOS-strix-B450i#25]
I have installed Big Sur and works fine and I feel more speed than  Catalina.
But when i play movies in Apple TV the screen turns on green . This issue had been fixit previously with Catalina. But now, with Big Sur this issue returns.

**Comment by willza3** [comment]
I think this is something I've broken and forgot to fix...

In your boot args can you add `shikigva=80` ?

(If it's already there just change the value to 80)

**Comment by Gizmo648** [comment]
I have change the value to 80 but doesn't works.

**Comment by willza3** [comment]
What GPU do you have?

**Comment by willza3** [comment]
Looks like this is down to WhateverGreen's DRM patches not working under Big Sur. I will keep this open until a fix is available.

**Comment by Gizmo648** [comment]
Thanks a lot , by the way GPU is Saphire Pulse Radeon RX570 (working fine with Catalina).

**Comment by Gizmo648** [comment]
Finally, I ve return to my old and stable Catalina. I hope new EFI will works fine. My issues was green screen on Apple TV and the usb wireless won't work, only ethernet . With Catalina works fine. Regards.
