### ISSUE TITLE
BCM94352z issue

### ISSUE THREAD

**Issue by swy680614** [willza3/macOS-strix-B450i#26]
Hi
First, Thank you for your efi.
Based on your efi.
I choose the same motherboard as you.
I used BCM94352z for my wifi/bt but not works.
May I know which wifi/bt card you used?
Thank you again.

**Comment by willza3** [comment]
I haven't replaced my card at the moment but this is something I will do in future, if you have Telegram there are a lot of helpful people in there which may be able to help you out 👍
