### ISSUE TITLE
MacOS 10.15.4 Update / Full Install

### ISSUE THREAD

**Issue by scottdrmyers** [willza3/macOS-strix-B450i#3]
Hardware:

Strix B450-I
16GB RAM @ 3600MHz
3600X @ Stock Clocks
5500XT using `agdpmod=pikera`
256GB SATA SSD

MacOS 10.15.3 installed without issues. Got prompted for MacOS 10.15.4 update within MacOS itself. Attempted installing. 

Asks to reboot to install, I reboot, 10.15.4 update does not get installed. Am I missing something?

I tried to do a full install (clean install) of 10.15.4 using the same EFI Folder, etc, but the install fails with an error (will try this again later to get the full output) but was something to the effect of "Intel_Processor_PENRYN" not found.

Willza3, were you able to install 10.15.4 either through an update or via a clean install?

Thanks for your work! :D

**Comment by simplelifeeee0** [comment]
You just have to use the updated kernel patch

**Comment by scottdrmyers** [comment]
> You just have to use the updated kernel patch

Sweet! Is there a guide or quick and easy way to do that? I'm all for learning, just some of this is new to me. Sounds easy anyway haha.

**Comment by scottdrmyers** [comment]
```
	<key>Base</key>
				<string></string>
				<key>Comment</key>
				<string>algrey - cpuid_set_cpufamily - force CPUFAMILY_INTEL_PENRYN</string>
				<key>Count</key>
				<integer>1</integer>
				<key>Enabled</key>
				<true/>
				<key>Find</key>
				<data>31db803d00000000067500</data>
				<key>Identifier</key>
				<string>kernel</string>
				<key>Limit</key>
				<integer>0</integer>
				<key>Mask</key>
				<data>ffffffff000000ffffff00</data>
				<key>MaxKernel</key>
				<string>19.99.99</string>
				<key>MinKernel</key>
				<string>17.0.0</string>
				<key>Replace</key>
				<data>bbbc4fea78e95d00000090</data>
				<key>ReplaceMask</key>
				<data></data>
				<key>Skip</key>
				<integer>0</integer>
```

So that's what I have in my config.plist.

Maybe I'm using the wrong one but I grabbed the info from here: https://www.reddit.com/r/hackintosh/comments/fo9bfv/macos_10154_update/


Error: https://imgur.com/a/sD6tnhe

**Comment by simplelifeeee0** [comment]
> > You just have to use the updated kernel patch
> 
> 
> 
> Sweet! Is there a guide or quick and easy way to do that? I'm all for learning, just some of this is new to me. Sounds easy anyway haha.

Yea for sure, just download these https://github.com/AMD-OSX/AMD_Vanilla

Open both files, 
Delete the Kernel -> Patch section from config.plist
Copy the Kernel -> Patch section from patches.plist
Paste into where old patches were in config.plist

**Comment by scottdrmyers** [comment]
> > > You just have to use the updated kernel patch
> > 
> > 
> > Sweet! Is there a guide or quick and easy way to do that? I'm all for learning, just some of this is new to me. Sounds easy anyway haha.
> 
> Yea for sure, just download these https://github.com/AMD-OSX/AMD_Vanilla
> 
> Open both files,
> Delete the Kernel -> Patch section from config.plist
> Copy the Kernel -> Patch section from patches.plist
> Paste into where old patches were in config.plist

That worked. Thanks!!!
