### ISSUE TITLE
iCloud issue

### ISSUE THREAD

**Issue by mlch911** [willza3/macOS-strix-B450i#4]
I installed macOS 10.15.4 after updating Patch. Everything works but iCloud. iMessage and FaceTime works. The iCloud folder is always empty.

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by scottdrmyers** [comment]
> I installed macOS 10.15.4 after updating Patch. Everything works but iCloud. iMessage and FaceTime works. The iCloud folder is always empty.
> 
> Sent from [PPHub](https://apps.apple.com/cn/app/id1314212521)

Do you mean for syncing files? I just tested mine, works fine here.

Did you change your serial number and such or just using the defaults from the config.plist located here?

------------------------------------

https://github.com/corpnewt/GenSMBIOS

Simply get GenSMBIOS, generate a new SMBIOS for model "imacpro1,1" -> It will give you some serial numbers, simply replace the serials in the PlatformInfo section of the config.plist and you're good to go.

```
<key>PlatformInfo</key>
<dict>
	<key>Automatic</key>
	<true/>
	<key>Generic</key>
	<dict>
		<key>AdviseWindows</key>
		<false/>
		<key>MLB</key>
		<string>C02023108J9JG36FB</string>
		<key>ROM</key>
		<data>ESIzAAAA</data>
		<key>SpoofVendor</key>
		<true/>
		<key>SystemProductName</key>
		<string>iMacPro1,1</string>
		<key>SystemSerialNumber</key>
		<string>C02CT01EHX87</string>
		<key>SystemUUID</key>
		<string>90D1BD15-E094-402B-84F5-F95A5376A8B6</string>
	</dict>
	<key>UpdateDataHub</key>
	<true/>
	<key>UpdateNVRAM</key>
	<true/>
	<key>UpdateSMBIOS</key>
	<true/>
	<key>UpdateSMBIOSMode</key>
	<string>Create</string>
</dict>
```

**Comment by mlch911** [comment]
> > I installed macOS 10.15.4 after updating Patch. Everything works but iCloud. iMessage and FaceTime works. The iCloud folder is always empty.
> > Sent from [PPHub](https://apps.apple.com/cn/app/id1314212521)
> 
> Do you mean for syncing files? I just tested mine, works fine here.
> 
> Did you change your serial number and such or just using the defaults from the config.plist located here?
> 
> https://github.com/corpnewt/GenSMBIOS
> 
> Simply get GenSMBIOS, generate a new SMBIOS for model "imacpro1,1" -> It will give you some serial numbers, simply replace the serials in the PlatformInfo section of the config.plist and you're good to go.
> 
> ```
> <key>PlatformInfo</key>
> <dict>
> 	<key>Automatic</key>
> 	<true/>
> 	<key>Generic</key>
> 	<dict>
> 		<key>AdviseWindows</key>
> 		<false/>
> 		<key>MLB</key>
> 		<string>C02023108J9JG36FB</string>
> 		<key>ROM</key>
> 		<data>ESIzAAAA</data>
> 		<key>SpoofVendor</key>
> 		<true/>
> 		<key>SystemProductName</key>
> 		<string>iMacPro1,1</string>
> 		<key>SystemSerialNumber</key>
> 		<string>C02CT01EHX87</string>
> 		<key>SystemUUID</key>
> 		<string>90D1BD15-E094-402B-84F5-F95A5376A8B6</string>
> 	</dict>
> 	<key>UpdateDataHub</key>
> 	<true/>
> 	<key>UpdateNVRAM</key>
> 	<true/>
> 	<key>UpdateSMBIOS</key>
> 	<true/>
> 	<key>UpdateSMBIOSMode</key>
> 	<string>Create</string>
> </dict>
> ```

I have changed these numbers at the beginning. And icloud still can't sync files.

**Comment by willza3** [comment]
Still not working? I've just checked and it's working fine for me, I've just pushed a new update so try that and see if it works :)

**Comment by mlch911** [comment]
> Still not working? I've just checked and it's working fine for me, I've just pushed a new update so try that and see if it works :)

Thanks a lot. After I reinstalled macOS and change the serial number, it works.
Now I have another problem... It only boot up into Bios, and there is two boot device on the same disk. These are the same.

**Comment by willza3** [comment]
@mlch911 - Have you tried clearing out your EFI folder and replacing it with a fresh copy of mine? Also try updating your BIOS. I'm not sure what else would be causing the issue otherwise 🙁
