### ISSUE TITLE
Not an issue just a suggestion

### ISSUE THREAD

**Issue by simplelifeeee0** [willza3/macOS-strix-B450i#6]
If you use shikigva=80 in the boot args it fixes Apple TV+ and all drm issues with this configuration

**Comment by Gizmo648** [comment]
I have this args
debug=0x100 keepsyms=1 npci=0x2000 alcid=7
do I need to change it ?

**Comment by simplelifeeee0** [comment]
Just add shikigva=80 and all dark content will work upon restart

**Comment by willza3** [comment]
Thanks for letting me know, just added the boot args and it worked with Netflix and Prime Video. Are you able to test with TV+? I have a subscription but the app isn't letting me log in.

**Comment by simplelifeeee0** [comment]
Appreciate it, just wanted to put it in there, lots of people don’t know about this arg but I’ve been using it for months netflix, Amazon, and Apple TV+
