### ISSUE TITLE
Cannot boot usb installer with this EFI

### ISSUE THREAD

**Issue by antech2020** [willza3/macOS-strix-B450i#8]
Hello, thank you for the files, I have B450-i strix mainboard, 2700x and I make USB stick installer using AMD OS X Vanilla Guide, then replace with your EFI, setting up BIOS as your guide except CSM enabled because otherwise it won't boot to usb and goes straight to windows.  When I tried to boot from USB installer it got  stucked at blinking cursor. Do you know how to fix that? Thanks/.

**Comment by willza3** [comment]
Have you tried using [this guide](https://dortania.github.io/OpenCore-Desktop-Guide/installer-guide/) instead of the AMD OS X one?
